# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JoeCode
description: Code with distinct characteristics traceable to its author.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joecode.com" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: joewils.github.com # the GitHub repo name for your project
github_username: joewils

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: instagram
social_username: joewils

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: blue

# Build settings
markdown: kramdown

# Google Analytics
google_analytics: UA-191795-1

# Permalink Style
permalink: /:year-:month-:day-:title/

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

paginate: 12
paginate_path: "noise/:num"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME